name: Golang CI

on:
  push:
    branches:
      - main

jobs:
  build:
    steps:
      - name: Install NodeJS and Golang
        run: sudo apk add --update nodejs npm go

      - name: Install pm2
        run: sudo npm install pm2@latest -g

      - name: Install depenendencies
        run: go mod tidy

      - name: Build Go App
        run: go build -o main

  deploy:
    steps:
      - name: Start App with pm2
        run: pm2 start -f "./main"

      - name: Save pm2 config
        run: pm2 save
