name: Express App Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    steps:
      - name: Install nodejs
        run: sudo apk add --update nodejs npm

      - name: Install Python3 and Pip3
        run: sudo apk add --no-cache python3=3.9.6-r0 py3-pip

      - name: Install depenendencies
        run: sudo pip3 install -r requirements.txt

      - name: Install pm2
        run: sudo npm install pm2@latest -g

  deploy:
    steps:
      - name: Start App with pm2
        run: pm2 start "python3 main.py"

      - name: Save pm2 config
        run: pm2 save
